 2019-07-01 04:34:41,060 [INFO] (MainThread) Program Started
 2019-07-01 04:34:41,068 [INFO] (MainThread) Reading usernames/passwords...
 2019-07-01 04:34:41,069 [INFO] (MainThread) Reading proxies...
 2019-07-01 04:34:41,070 [INFO] (MainThread) Reading message options...
 2019-07-01 04:34:41,078 [INFO] (Proxy Validator - 0) Validating proxy : 178.206.225.2:3128 ...
 2019-07-01 04:34:41,085 [INFO] (Proxy Validator - 1) Validating proxy : 188.43.20.177:3128 ...
 2019-07-01 04:34:59,194 [WARNING] (Proxy Validator - 1) BAD PROXY : 188.43.20.177:3128
 2019-07-01 04:34:59,198 [WARNING] (Proxy Validator - 1) Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f50825fc990>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/bf734243603b58d93b477b4664e49be4
 2019-07-01 04:34:59,199 [WARNING] (Proxy Validator - 1) Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5081181e10>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/bf734243603b58d93b477b4664e49be4
 2019-07-01 04:34:59,203 [WARNING] (Proxy Validator - 1) Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5081181f50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/bf734243603b58d93b477b4664e49be4
